version: "3.8"
services:
  db:
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - rails_react_apollo_db:/var/lib/postgresql/data
    networks:
      - rails_react_apollo_net

  webpacker:
    image: ${DOCKER_IMAGE_NAME-rails_react_apollo}
    command: ["./scripts/start_webpack_dev.sh"]
    volumes:
      - .:/opt/rails-react-apollo:cached
    ports:
      - 3035:3035
    networks:
      - rails_react_apollo_net

  web:
    image: ${DOCKER_IMAGE_NAME-rails_react_apollo}
    build:
      context: .
      args:
        precompileassets: "not"
    ports:
      - 3000:3000
    command:
      ["./scripts/wait-for-it.sh", "db:5432", "--", "./scripts/start_rails.sh"]
    volumes:
      - .:/opt/rails-react-apollo:cached
    networks:
      - rails_react_apollo_net
volumes:
  rails_react_apollo_db:
networks:
  rails_react_apollo_net:
