default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_USER_PASSWORD'] %>

development:
  <<: *default
  database: rra_development

test:
  <<: *default
  database: rra_test
